-- AlterTable
ALTER TABLE `users` MODIFY `firstname` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `lastname` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `name` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `picture` VARCHAR(191) NOT NULL DEFAULT '';
